### ISSUE TITLE
pytest error

### ISSUE THREAD

**Issue by HenrikBengtsson** [MetabolicEngineeringGroupCBMA/seguid#19]
# Details

```sh
$ git checkout bjorn
Your branch is up to date with 'origin/bjorn'.

$ git log -1
commit 14e270881584d558b672cd4b9125c917d46b1e1a (HEAD -> bjorn, origin/bjorn)
Author: BjornFJohansson <bjornjobb@gmail.com>
Date:   Wed Dec 13 23:33:45 2023 +0000

    all tests passes

$ python --version
Python 3.10.12

$ pip install --editable . --no-deps
Defaulting to user installation because normal site-packages is not writeable
Obtaining file:///home/henrik/repositories/seguid/Python
  Installing build dependencies ... done
  Checking if build backend supports build_editable ... done
  Getting requirements to build editable ... done
  Preparing editable metadata (pyproject.toml) ... done
Building wheels for collected packages: seguid
  Building editable for seguid (pyproject.toml) ... done
  Created wheel for seguid: filename=seguid-0.0.1-py3-none-any.whl size=2357 sha256=a7fb2ee49dd2ae5d7c6e98b973bc0273b6d7d348cff18f07206755190346d36b
  Stored in directory: /tmp/henrik/pip-ephem-wheel-cache-836n2xha/wheels/f9/d3/79/926d4a582ebcaab0091785a7235f962c92d9fa2596ddab537d
Successfully built seguid
Installing collected packages: seguid
  Attempting uninstall: seguid
    Found existing installation: seguid 0.0.1
    Uninstalling seguid-0.0.1:
      Successfully uninstalled seguid-0.0.1
Successfully installed seguid-0.0.1
```

```sh
$ pytest --version
pytest 7.3.2

$ pytest
cwd set to /home/henrik/repositories/seguid/Python/tests in /home/henrik/repositories/seguid/Python/tests/conftest.py
================================================= test session starts ==================================================
platform linux -- Python 3.10.12, pytest-7.3.2, pluggy-1.0.0
rootdir: /home/henrik/repositories/seguid/Python
configfile: pytest.ini
plugins: anyio-3.7.0
collected 19 items                                                                                                     

src/seguid/chksum.py .F...
src/seguid/manip.py ...
tests/tests.py ........F.F

======================================================= FAILURES =======================================================
___________________________________________ [doctest] seguid.chksum.scseguid ___________________________________________
225     Only defined for circular sequences.
226 
227     The srfun argument has to take a string as an argument and
228     return another string.
229 
230     The checksum is prefixed with "scseguid:"
231 
232     Examples
233     --------
234     >>> scseguid("ATTT")
UNEXPECTED EXCEPTION: TypeError("catch_warnings.__init__() got an unexpected keyword argument 'category'")
Traceback (most recent call last):
  File "/usr/lib/python3.10/doctest.py", line 1350, in __run
    exec(compile(example.source, filename, "single",
  File "<doctest seguid.chksum.scseguid[0]>", line 1, in <module>
  File "/home/henrik/repositories/seguid/Python/src/seguid/chksum.py", line 244, in scseguid
    start = min_rotation(seq)
  File "/home/henrik/repositories/seguid/Python/src/seguid/chksum.py", line 48, in min_rotation
    with warnings.catch_warnings(category=UserWarning):
TypeError: catch_warnings.__init__() got an unexpected keyword argument 'category'
/home/henrik/repositories/seguid/Python/src/seguid/chksum.py:234: UnexpectedException
____________________________________________________ test_scseguid _____________________________________________________

    def test_scseguid():
        m13dna = Path("M13.txt").read_text().strip()
        sc = "scseguid:aAjgnsF9cPI6cu8IQ81sYnstVzU"
>       assert scseguid(m13dna) == sc

/home/henrik/repositories/seguid/Python/tests/tests.py:141: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
/home/henrik/repositories/seguid/Python/src/seguid/chksum.py:244: in scseguid
    start = min_rotation(seq)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

s = 'AACGCTACTACTATTAGTAGAATTGATGCCACCTTTTCAGCTCGCGCCCCAAATGAAAATATAGCTAAACAGGTTATTGACCATTTGCGAAATGTATCTAATGGTCAAACTAAATCT...CGCAAAAGTATTACAGGGTCATAATGTTTTTGGTACAACCGATTTAGCTTTATGCTCTGAGGCTTTATTGCTTAATTTTGCTAATTCTTTGCCTTGCCTGTATGATTTATTGGATGTT'

    def min_rotation(s):
>       with warnings.catch_warnings(category=UserWarning):
E       TypeError: catch_warnings.__init__() got an unexpected keyword argument 'category'

/home/henrik/repositories/seguid/Python/src/seguid/chksum.py:48: TypeError
____________________________________________________ test_dcseguid _____________________________________________________

    def test_dcseguid():
        pUC19dna = Path("puc19.txt").read_text().strip()
        dcsg = "dcseguid:zhw8Yrxfo3FO5DDccx4PamBVPCQ"
>       assert dcseguid(pUC19dna, rc(pUC19dna)) == dcsg

/home/henrik/repositories/seguid/Python/tests/tests.py:197: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
/home/henrik/repositories/seguid/Python/src/seguid/chksum.py:377: in dcseguid
    x = min_rotation(watson)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

s = 'TCGCGCGTTTCGGTGATGACGGTGAAAACCTCTGACACATGCAGCTCCCGGAGACGGTCACAGCTTGTCTGTAAGCGGATGCCGGGAGCAGACAAGCCCGTCAGGGCGCGTCAGCGG...AATAAACAAATAGGGGTTCCGCGCACATTTCCCCGAAAAGTGCCACCTGACGTCTAAGAAACCATTATTATCATGACATTAACCTATAAAAATAGGCGTATCACGAGGCCCTTTCGTC'

    def min_rotation(s):
>       with warnings.catch_warnings(category=UserWarning):
E       TypeError: catch_warnings.__init__() got an unexpected keyword argument 'category'

/home/henrik/repositories/seguid/Python/src/seguid/chksum.py:48: TypeError
=============================================== short test summary info ================================================
FAILED src/seguid/chksum.py::seguid.chksum.scseguid
FAILED tests/tests.py::test_scseguid - TypeError: catch_warnings.__init__() got an unexpected keyword argument 'category'
FAILED tests/tests.py::test_dcseguid - TypeError: catch_warnings.__init__() got an unexpected keyword argument 'category'
============================================= 3 failed, 16 passed in 0.15s =============================================
```

**Comment by HenrikBengtsson** [comment]
Never mind. Folder was probably corrupted by other local things of mine.  When cloning a new, clean repo, I get:

```sh
$ pytest 
cwd set to /home/henrik/repositories/seguid/Python/tests in /home/henrik/repositories/seguid/Python/tests/conftest.py
===================================== test session starts =====================================
platform linux -- Python 3.10.12, pytest-7.3.2, pluggy-1.0.0
rootdir: /home/henrik/repositories/seguid/Python
configfile: pytest.ini
plugins: anyio-3.7.0
collected 22 items                                                                            

seguid.py ..........
tests/tests.py ............

====================================== warnings summary =======================================
tests/tests.py::test_dcseguid
tests/tests.py::test_scseguid
  /home/henrik/repositories/seguid/Python/seguid.py:115: UserWarning: converting str argument uses more memory
    k = min_rotation(s)

-- Docs: https://docs.pytest.org/en/stable/how-to/capture-warnings.html
=============================== 22 passed, 2 warnings in 0.07s ================================
```

**Comment by HenrikBengtsson** [comment]
I've added a GitHub Actions pytest job; it reproduces these error, cf. <https://github.com/MetabolicEngineeringGroupCBMA/seguid/actions/runs/7202538407/job/19620846863>.

**Comment by BjornFJohansson** [comment]
I develop on Python 3.11, did not catch that this was a new addition:

https://docs.python.org/3/library/warnings.html#available-context-managers

"Changed in version **3.11**: Added the action, category, lineno, and append parameters."
