### ISSUE TITLE
Empty input should be an error

### ISSUE THREAD

**Issue by HenrikBengtsson** [MetabolicEngineeringGroupCBMA/seguid#46]
While adding tests for #30, I spotted the following empty-input bugs:

```r
$ Rscript -e 'seguid::dlseguid("", "", overhang = 0)'
Error in assert_anneal(watson, crick, overhang = overhang, table = table) : 
  -nchar(watson) < overhang is not TRUE

$ Rscript -e 'seguid::dcseguid("", "")'
Error in assert_anneal(watson, crick, overhang = 0, table = table) : 
  -nchar(watson) < overhang is not TRUE
```

```py
$ python -c 'from seguid.chksum import *; dlseguid("", "", overhang = 0)'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/henrik/.local/lib/python3.10/site-packages/seguid/chksum.py", line 236, in dlseguid
    assert_anneal(watson, crick, overhang, table=table)
  File "/home/henrik/.local/lib/python3.10/site-packages/seguid/asserts.py", line 56, in assert_anneal
    assert -len(watson) < overhang, "watson and crick has to anneal with at least one bp"
AssertionError: watson and crick has to anneal with at least one bp

$ python -c 'from seguid.chksum import *; dcseguid("", "")'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/henrik/.local/lib/python3.10/site-packages/seguid/chksum.py", line 265, in dcseguid
    assert_anneal(watson, crick, 0, table=table)
  File "/home/henrik/.local/lib/python3.10/site-packages/seguid/asserts.py", line 56, in assert_anneal
    assert -len(watson) < overhang, "watson and crick has to anneal with at least one bp"
AssertionError: watson and crick has to anneal with at least one bp
```

**Comment by BjornFJohansson** [comment]
What should these give? A better error msg?

**Comment by HenrikBengtsson** [comment]
> What should these give? A better error msg?

I wonder if they should return a checksum just like `seguid("")` and `lsseguid("")` do.

**Comment by BjornFJohansson** [comment]
I think an error is better. This catch the possibility of empty strings being fed by mistake?

**Comment by HenrikBengtsson** [comment]
Works for me too; then we should do the same for all functions.

**Comment by HenrikBengtsson** [comment]
... and I think we should check for empty input and give an informative error message.

**Comment by HenrikBengtsson** [comment]
I've updated R accordingly;

```sh
$ Rscript -e "seguid::seguid('')"
Error in seguid::seguid("") : A sequence must not be empty
Execution halted

$ Rscript -e "seguid::slseguid('')"
Error in seguid::slseguid("") : A sequence must not be empty
Execution halted

$ Rscript -e "seguid::scseguid('')"
Error in seguid::scseguid("") : A sequence must not be empty
Execution halted

$ Rscript -e "seguid::dlseguid('', '', overhang=0)"
Error in seguid::dlseguid("", "", overhang = 0) : A sequence must not be empty
Execution halted

$ Rscript -e "seguid::dcseguid('', '')"
Error in seguid::dcseguid("", "") : A sequence must not be empty
Execution halted
```

**Comment by HenrikBengtsson** [comment]
It looks like you completed this. Is that correct?

**Comment by BjornFJohansson** [comment]
test_empty() in test_chksum.py
